Update build-workflow.yml

diff --git a/.github/workflows/build-workflow.yml b/.github/workflows/build-workflow.yml
--- a/.github/workflows/build-workflow.yml
+++ b/.github/workflows/build-workflow.yml
@@ -113,14 +113,17 @@ jobs:
                         --output text)
               echo "Current Instance Refresh Status: $status"
             done
-      
+                   if [ "$status" != "Successful" ]; then
+                     echo "Instance refresh failed. Exiting workflow with an error."
+                     exit 1
+                   else
+                      echo "Instance Refresh Status: Successful"
+                   fi
+                     
 
-          if [ "$status" != "Successful" ]; then
-            echo "Instance refresh failed. Exiting workflow with an error."
-            exit 1
-          else
-            echo "Instance Refresh Status: Successful"
-          fi
+
+
+
 
 
 
