Feature branch (#67)
* updated

* Update aws-debian.yml

* Update aws-debian.yml

* Create aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update app.yml

* Update build-workflow.yml

* Update app.yml

* Update README.md

* Update README.md

* Update build-workflow.yml

* Update README.md

* Update build-workflow.yml

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update README.md

* Update aws-debian.pkr.hcl

* Update README.md

* Update aws-debian.pkr.hcl

* Update README.md

* Update README.md

* Update build-workflow.yml

* Update aws-debian.pkr.hcl

* Update README.md

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update README.md

* Update README.md

* Update aws-debian.pkr.hcl

* Update README.md

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* Update README.md

* Update build-workflow.yml

* Update build-workflow.yml

* Update README.md

* Update build-workflow.yml

* Update README.md

* Update build-workflow.yml

* Update README.md

* Update README.md

* updated

* updated

* oo

* updated

* updated packer

* updated the service file path

* File path changed

* file path changed

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* updated packer

* updated

* autostart commands added

* commands updated

* fix the user permissions

* updated

* updated

* updated

* updated

* updated

* demo

* Update build-workflow.yml

* Update aws-debian.pkr.hcl

* Update aws-debian.pkr.hcl

* updated

* updated

* Update app.service

* Update aws-debian.pkr.hcl

* updated cloudwatch packer

* updated

* removed logger command

* updated

* updated

* updated

* addede statsD

* updated

* updated

* UPDATED

* updated

* updated

* updated

* Update aws-debian.pkr.hcl

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* updated

* Update aws-debian.pkr.hcl

* Update build-workflow.yml

* Update aws-debian.pkr.hcl

* updated

* Update build-workflow.yml

* Update build-workflow.yml

* Update build-workflow.yml

* Update build-workflow.yml

* Update build-workflow.yml

MINOR CHANGES

diff --git a/.github/workflows/build-workflow.yml b/.github/workflows/build-workflow.yml
--- a/.github/workflows/build-workflow.yml
+++ b/.github/workflows/build-workflow.yml
@@ -110,19 +110,19 @@ jobs:
             status=$(aws autoscaling describe-instance-refreshes \
 
                       --auto-scaling-group-name "$asg_name" \
-
-
                       --query 'InstanceRefreshes[0].Status' \
                       --output text)
           echo "Current Instance Refresh Status: $status"
           done
     
-                if [ "$status" != "Successful" ]; then
-                  echo "Instance refresh failed. Exiting workflow with an error."
-                  exit 1
-                else
-                  echo "Instance Refresh Status: Successful"
-                fi
+
+          if [ "$status" != "Successful" ]; then
+            echo "Instance refresh failed. Exiting workflow with an error."
+            exit 1
+          else
+            echo "Instance Refresh Status: Successful"
+          fi
+
 
 
 
