Update build-workflow.yml

diff --git a/.github/workflows/build-workflow.yml b/.github/workflows/build-workflow.yml
--- a/.github/workflows/build-workflow.yml
+++ b/.github/workflows/build-workflow.yml
@@ -113,15 +113,15 @@ jobs:
 
                       --query 'InstanceRefreshes[0].Status' \
                       --output text)
+          echo "Current Instance Refresh Status: $status"
           done
-      - name: Check Instance Refresh Status
-        run: |
-          # Add commands to check the instance refresh status
-          echo "Instance Refresh Status: ${{ steps.wait-for-refresh.outputs.status }}"
-          if [ "${{ steps.wait-for-refresh.outputs.status }}" != "Successful" ]; then
-            echo "Instance refresh failed. Exiting workflow with an error."
-            exit 1
-          fi
+    
+                if [ "$status" != "Successful" ]; then
+                  echo "Instance refresh failed. Exiting workflow with an error."
+                  exit 1
+                else
+                  echo "Instance Refresh Status: Successful"
+                fi
 
 
 
